plugins {
    id 'java'
    id 'application'
    id "io.freefair.lombok" version "8.11"
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'cc.hrva.url'
version = '1.4.1'
description = 'Url Shortener'

repositories {
    mavenCentral()
}

ext {
    set('springBootVersion', '3.4.1')
    set('springdocVersion', '2.8.5')
    set('jsonwebtokenVersion', '0.11.5')
    set('apacheCommonsVersion', '3.17.0')
    set('commonsIoVersion', '2.18.0')
    set('googleApiClientVersion', '2.7.1')
    set('googleApiServicesSafebrowsingVersion', 'v4-rev20230212-2.0.0')
    set('jacksonJsr310Version', '2.18.2')
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework:spring-context-support'
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonJsr310Version}"

    runtimeOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'

    compileOnly 'org.projectlombok:lombok'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"
    implementation "io.jsonwebtoken:jjwt-api:${jsonwebtokenVersion}"
    implementation "io.jsonwebtoken:jjwt-impl:${jsonwebtokenVersion}"
    implementation "io.jsonwebtoken:jjwt-jackson:${jsonwebtokenVersion}"
    implementation "org.apache.commons:commons-lang3:${apacheCommonsVersion}"
    implementation "commons-io:commons-io:${commonsIoVersion}"
    implementation 'org.liquibase:liquibase-core'
    implementation "com.google.api-client:google-api-client:${googleApiClientVersion}"
    implementation "com.google.apis:google-api-services-safebrowsing:${googleApiServicesSafebrowsingVersion}"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}

jar {
    enabled = false
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.register('stage') {
    dependsOn('build')
    doLast {
        java.sourceSets.main.each { src ->
            copy {
                from src.output
                into project.file('build/libs')
            }
        }
    }
}

test {
    useJUnitPlatform()
}
