spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  application:
    name: URL Shortener DevMode

server:
  port: 8080
  error:
    include-message: always

frontend:
  url: http://localhost:4200
