spring:
  liquibase:
    change-log: classpath:/db/dbchangelog.xml
  data:
    redis:
      host: redis.hrvalabs.net
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:}
            scope: profile, email
            redirect-uri: https://hrva.cc/login/oauth2/code/google
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID:}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET:}
            scope: user:email
            redirect-uri: https://hrva.cc/login/oauth2/code/github
  web:
    error:
      include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,env,beans
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized

server:
  forward-headers-strategy: framework

app:
  app-name: hrva.cc Url Shortener
  google-api:
    client-id: hrva.cc
    client-version: 1.0.0
  short-url-length: 5
  api-key-calls-limit: 256
  jwt-token-validity-seconds: 36000
  api-key-expiration-in-months: 12
  reset-token-expiration-in-hours: 24
  user-api-key-slots: 4
  inactive-visit-increment-per-ip-in-hours: 2
  ip-retention-duration-in-hours: 48
  deactivate-user-account-after-days: 1825
  max-login-attempts: 20
  url-expiration-notification-hours: 24
  registration-enabled: true
  anonymous-url-creation-enabled: false
