spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  liquibase:
    change-log: classpath:/db/dbchangelog.xml
management:
  endpoints:
    web:
      exposure:
        include: "health, info"
server:
  error:
    include-message: always