spring:
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "health, info"

server:
  error:
    include-message: always