spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: false
  application:
    name: URL Shortener DevMode
  mail:
    host: test.com
    port: 0
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
app:
  short-url-length: 5
  api-key-length: 12
  api-key-calls-limit: 8
  jwt-token-validity-seconds: 3600
  api-key-expiration-in-months: 1
  jwt-base64-secret: MzMzYjg3YTRmYmU0YmM4YzJkZWE4NTJlZGEzMDgzZjkzOWNjM2MwMWQ4NzI2MjgwZWU0MzM5ZTY0MGEzMjg1YzIwMjU1MWM5ZTNkMzg5YWNiMjExNGJlMTE4NjZlMWMxODIxNjYwMTBkZTRiZWRlNzU3MDc5ZThhMDcxMjlkMGE
  email-sender-address: oncut@oncut.me
server:
  port: 8080
