spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: false
  application:
    name: URL Shortener DevMode
  mail:
    host: smtp.mailgun.org
    port: 587
    username:  postmaster@sandbox5a4e29f472fe4aca8089b50a397499d7.mailgun.org
    password: 834fd6e73b80cf6ac6c824ab32a22bcf
    properties:
      mail:
        smtp:
          auth: true
app:
  short-url-length: 5
  api-key-length: 12
  api-key-calls-limit: 8
  jwt-token-validity-seconds: 36000
  api-key-expiration-in-months: 1
  jwt-base64-secret: MzMzYjg3YTRmYmU0YmM4YzJkZWE4NTJlZGEzMDgzZjkzOWNjM2MwMWQ4NzI2MjgwZWU0MzM5ZTY0MGEzMjg1YzIwMjU1MWM5ZTNkMzg5YWNiMjExNGJlMTE4NjZlMWMxODIxNjYwMTBkZTRiZWRlNzU3MDc5ZThhMDcxMjlkMGE
  email-sender-address: oncut@oncut.me
  reset-token-expiration-in-hours: 1
server:
  port: 8080
