services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=url_shortener
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'

volumes:
  db:
    driver: local