name: url-shortener
services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=url_shortener
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql

  redis:
    image: redis:8
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  db:
    driver: local
