name: Build images

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle and Jib
        run: ./gradlew clean build

      - name: JIB container build and publish
        uses: MathieuSoysal/jib-container-publish.yml@v2.1.3
        with:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build