name: Dev Branch Workflow

on:
  push:
    branches: [ dev ]

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}